### ISSUE TITLE
Predicting winning cell for data?

### ISSUE THREAD

**Issue by imariasantos** [fcomitani/simpsom#13]
Once the SOM has been trained, is it possible to get the cell to which a data sample belongs? Or for each cell to get a list of samples from a dataset that belong to that cell? I haven't found anything like this in the example.

**Comment by fcomitani** [comment]
Hi @imariasantos,

you are right, this is not very clear in the current example.

The `project` function project the data onto the trained map and also returns a list with the bmu coordinates of each sample. You can set `printout` as `False` if you don't want to plot the data.

It should look something like this:

`coord = net.project(raw_data, printout=False)`

Alternatively, if you want specifically the bmu object, you can run `findBmu` for each sample. 

`singleBmu= net.findBmu(samplearray)`

the output is a `somNode` type from which you can get position (e.g. `singleBmu.pos`) or weights (`singleBmu.weights`).

**Comment by fcomitani** [comment]
If there's nothing else, I'm closing this issue.
