### ISSUE TITLE
Parallelization of the code

### ISSUE THREAD

**Issue by Abelardo2** [fcomitani/simpsom#16]
Hi, first thanks for the code, I'm using it at my work for clustering some data.
I'm interested in parallelizing the code, and I see that you have a "TODO" comment above this line "Parallel(n_jobs=self.n_jobs)(delayed(my_func)(c, K, N) for c in inputs)" in the train function. I suppose you have tried or have some ideas about it, and I wanted to know which function is "my_func" a placeholder for, and what are the parameters c,K,N ir order to have a better general idea about how to proceed with the parallelization.

Again thanks for the repository!

**Comment by fcomitani** [comment]
Hi @Abelardo2,

thanks for your message. 

I was initially planning to parallelize the code with `joblib` (hence the commented line, `my_func` and the parameters are just placeholders). I haven't looked at it in a while, so I'm not even sure that's necessarily the best library. Considering there are different strategies to parallelize SOM, the choice may also depend on which way one goes, so I'm open to suggestions.

If you are interested in parallelizing the code I'll be more than happy to help and support the effort.

**Comment by fcomitani** [comment]
This has been now implemented in v2.0.0
