### ISSUE TITLE
Nodes difference MNIST

### ISSUE THREAD

**Issue by PARODBE** [fcomitani/simpsom#19]
Hi,

First at all, thank you for share the code. Could you share any code for nodes difference of MNIST? I am interesting on the representation by class just like your last image in the examples. And another question could you put centroids for the differents regions for each data point and finally calculate the distance for each data point with its centroid. And finally it is possible use SimpSOM like prediction? It would be very nice to see where a new point will be. Thanks for all!

**Comment by fcomitani** [comment]
Hi @PARODBE,

thanks for checking out the library.

The nodes differences plot can be printed with the `differences=net.diff_graph()`, which is a function of your map object `net`. It gives as output (`differences` in this example) a list with the difference values calculated for each node. I know that there are different ways of calculating it, so if you want the freedom to define your own difference function you can just use `node.get_distance()`, which is an attribute of each node and calculates its Euclidean distance to any other node.

Regarding your last question, yes, `reduced=net.project(input_data)` actually can project any kind of data (assuming it's in the right format) and can be used for prediction. Once you have trained your map `net` you can just give your new samples in input to this function and it will project them onto the map. It gives in output (`reduced` in the example ) the position of your data points in the reduced map space. You can then run any kind of clustering/classification function you wish on the projected data. If you want to try and run one of the internal clustering methods just use `net.cluster(input_data, type='qthresh')`. As clustering type it takes `'qthresh'` for quality threshold, `'dpeak'` for density peak, `'MeanShift' `, `'DBSCAN'`, and `'KMeans'` as directly taken from scikit-learn.    
Once you have the coordinates on the data you can calculate centroids and their distances.

Hope this answers your questions, let me know if you have any doubt.
