### ISSUE TITLE
pip version doesn't have colnames parameter in nodes_graph

### ISSUE THREAD

**Issue by Jorgvt** [fcomitani/simpsom#21]
Hi! 

I just realized that the version I installed from pip (`pip install SimpSOM`) doesn't have the `colnames` parameter included but it's included in the repo code. I made the modifications on my local file, but just so you know that happens! 

Thanks for your amazing work!

**Comment by fcomitani** [comment]
Hi @Jorgvt,

Apologies for the slow reply. Thank you for your message. Yes I believe that was fixed a while back, but I was waiting for more substantial changes before pushing a new version to pip. It's been a while now, so it may be worth doing it anyway.
