### ISSUE TITLE
Module Not Found error during import

### ISSUE THREAD

**Issue by jgericardo** [fcomitani/simpsom#24]
Hello! Thank you for your work. I tried importing the latest version of `simpsom` (v2.0.0) and the error occurred: `ModuleNotFoundError: No module named 'simpsom.cluster'`. There seems to be a missing **__init__.py** file in "./simpsom/cluster/". I tried adding it locally and it did the trick for me.

**Comment by fcomitani** [comment]
Of course I forgot the init file after all the testing! 
Thanks for spotting that, I'm going to push a patch later today!

**Comment by fcomitani** [comment]
This has been solved in v2.0.1 ddc13f6

Thanks again for letting me know and apologies for the inconvenience.
Feel free to reopen this issue if you are still having issues.
