### ISSUE TITLE
PyPi not using latest changes

### ISSUE THREAD

**Issue by christoffjordaan** [fcomitani/simpsom#27]
Hi @fcomitani 
I just want to inform you that PyPi does not pull the latest changes that include the `printout` typo fix.

**Comment by fcomitani** [comment]
Hi @christoffjordaan,

thanks for letting me know. We are about to release a new major version, I will make sure to release the bugfix on PyPI before that for backward compatibility.

**Comment by fcomitani** [comment]
v2.0.2 has been released, see [dbd4613](https://github.com/fcomitani/simpsom/commit/dbd4613e2ec1282da685ef02fc251a3ade88b15b)
