### ISSUE TITLE
problem due cyclical error?

### ISSUE THREAD

**Issue by lucasemmoreira** [fcomitani/simpsom#34]
Hi there!

I am trying to reproduce a simple example but I am having some issues to initialize SOMNet

To reproduce
```python
import simpsom as sps
import numpy as np

data = np.random.rand(20, 20)
net = sps.SOMNet(20, 20, data, topology='hexagonal',
                init='PCA', metric='cosine',
                neighborhood_fun='gaussian', PBC=True,
                random_seed=32, GPU=False, CUML=False,
                output_path="./")
```

and here is the error I get

```
Traceback (most recent call last):
  File "/home/lucas/mba/python/simpsom.py", line 1, in <module>
    import simpsom as sps
  File "/home/lucas/mba/python/simpsom.py", line 5, in <module>
    net = sps.SOMNet(20, 20, data, topology='hexagonal',
AttributeError: partially initialized module 'simpsom' has no attribute 'SOMNet' (most likely due to a circular import)

```

**Comment by fcomitani** [comment]
Hi @lucasemmoreira, thank you for reporting this.

I've never seen this before, I will look into it.
Could you tell me which version of Python are you running? Did you install `simpsom` through `pypi` or by cloning the repo?

**Comment by lucasemmoreira** [comment]
No problem!

The python version is 3.10.6. Yes, I installed via pip and it went wrong.

However, when I installed via source, I could run the library with no issues.

**Comment by fcomitani** [comment]
Glad to hear it's fixed in the last version. Thanks for the update.

I'm gonna close this issue but feel free to reopen it if the problem appears again.
