### ISSUE TITLE
Unbound Local Error While training

### ISSUE THREAD

**Issue by inder-preet-kakkar** [fcomitani/simpsom#5]
Hi, I tried training a model and I got the following error.

Training SOM... 0% 
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-8-5aadbad106a4> in <module>()
----> 1 net.train(0.2, 1000)

~\Anaconda3\lib\site-packages\simpsom-1.3.3-py3.7.egg\SimpSOM\__init__.py in train(self, startLearnRate, epochs)
    213             inputVec = self.data[np.random.randint(0, self.data.shape[0]), :].reshape(np.array([self.data.shape[1]]))
    214 
--> 215             bmu=self.find_bmu(inputVec)
    216 
    217             for node in self.nodeList:

~\Anaconda3\lib\site-packages\simpsom-1.3.3-py3.7.egg\SimpSOM\__init__.py in find_bmu(self, vec)
    173                 minVal=dist
    174                 bmu=node
--> 175         return bmu
    176 
    177 

UnboundLocalError: local variable 'bmu' referenced before assignment

**Comment by fcomitani** [comment]
Hello @Inder95,

It seems that when checking for the closest node to your input datapoints no distance passes the following `if` condition. 

```
        minVal=np.iinfo(np.int).max
        for node in self.nodeList:
            dist=node.get_distance(vec)
            if dist < minVal:
                minVal=dist
                bmu=node
        return bmu  
```
Is your data range very wide? It may be that the initial distances surpass the limit of `minVal`.

I increased the reference value to the machine limits for float. This should do the trick. 
Alternatively, you can normalize your data to reduce the variance.

Try installing and running the last version (1.3.4) form here on github and see if it works now.

**Comment by inder-preet-kakkar** [comment]
Thanks it still showed the same error but normalizing did the job. Thanks!

**Comment by kuyu12** [comment]
happened also to me

```
import SimpSOM as sps
net = sps.somNet(20, 20, cleanDataSet, PBC=True)
net.train(0.01, 100000)
**/usr/local/lib/python3.6/dist-packages/SimpSOM/__init__.py in find_bmu(self, vec)
UnboundLocalError: local variable 'bmu' referenced before assignmen**
```

How can I solve it? 

my Data is after StandardScaler (data between -1 to 1 )

**Comment by kuyu12** [comment]
Found sorry, the issue was with nan in the data
