### ISSUE TITLE
How to reference this package

### ISSUE THREAD

**Issue by rjverar** [fcomitani/simpsom#7]
Hi this code is pretty useful for making a fast SOM in a preliminary data set. I liked a lot, as the package can be also easily modified to change the graphics for my particular use. I wanted to ask you, how can your code be properly referred to a paper. Is there a publication from you that I shall cite, and if not, what shall I add to the acknowledgement section of my paper. Thanks!

**Comment by fcomitani** [comment]
Hi @rjverar,

I'm glad to hear that it was helpful!

There is no paper at the moment, but I added a DOI to the latest release and you can use that to cite it. You can generate a citation in different styles at the bottom of this [page](https://zenodo.org/badge/latestdoi/91130860).

Thanks!
