### ISSUE TITLE
a little error happened on densitypeak.py

### ISSUE THREAD

**Issue by SagacitySucura** [fcomitani/simpsom#8]
Near 284 line，p.dists.iteritems should change to p.dists.item. Thank you very mach for your code to help me a lot.

**Comment by fangxu622** [comment]
hi~~for why ？Now i'm want use som for cluster~Is this a bug?

**Comment by SagacitySucura** [comment]
may be this problem. You can have a try

**Comment by fcomitani** [comment]
Hi @SagacitySucura, thanks for spotting that. Indeed iteritems is not available in Pyhon 3.x. I am changing it to items.

Hi @fangxu622, I'm going to fix this, but in the meantime you can still use the alternative clustering methods included in the package, or, if you really need density peak, you could just run it with Python 2.x, which is not affected by this bug.
